# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/nonlinearthink"

[social.params]
icon = "brand-github"

[[social]]
identifier = "zhihu"
name = "知乎"
url = "https://www.zhihu.com/people/neweden-85"

[social.params]
icon = "brand-zhihu"
